services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

    command: sh -c "if [ -z \"$$APP_KEY\" ]; then export APP_KEY=base64:$$(php -r 'echo base64_encode(random_bytes(32));'); fi; php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: technical_test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
